#ifndef D_PINS_H
#define D_PINS_H

/* USART */

#define GPIO_USART_RXD		PD0
#define GPIO_USART_RXD_DDR	DDRD
#define GPIO_USART_RXD_PORT	PORTD

#define GPIO_USART_TXD		PD1
#define GPIO_USART_TXD_DDR	DDRD
#define GPIO_USART_TXD_PORT	PORTD

/* SYSCLK */

#define GPIO_SYSCLK_IN		PD2
#define GPIO_SYSCLK_IN_DDR	DDRD
#define GPIO_SYSCLK_IN_PORT	PORTD
#define GPIO_SYSCLK_IN_PIND	PIND

/* SIPO */

#define GPIO_SIPOSHR_CLK	PD5
#define GPIO_SIPOSHR_CLK_DDR	DDRD
#define GPIO_SIPOSHR_CLK_PORT	PORTD

#define GPIO_SIPOSHR_OUT	PD7
#define GPIO_SIPOSHR_OUT_DDR	DDRD
#define GPIO_SIPOSHR_OUT_PORT	PORTD

#define GPIO_SIPOSHR_RST	PD6
#define GPIO_SIPOSHR_RST_DDR	DDRD
#define GPIO_SIPOSHR_RST_PORT	PORTD

/* PISO */

#define GPIO_PISOSHR_CLK	PC0
#define GPIO_PISOSHR_CLK_DDR	DDRC
#define GPIO_PISOSHR_CLK_PORT	PORTC

#define GPIO_PISOSHR_LOAD	PC1
#define GPIO_PISOSHR_LOAD_DDR	DDRC
#define GPIO_PISOSHR_LOAD_PORT	PORTC

#define GPIO_PISOSHR_Q		PC2
#define GPIO_PISOSHR_Q_DDR	DDRC
#define GPIO_PISOSHR_Q_PORT	PORTC

/* Key Change Interrupt */

#define GPIO_KCI_OUT		PC3
#define GPIO_KCI_OUT_DDR	DDRC
#define GPIO_KCI_OUT_PORT	PORTC

/* TWI */

#define GPIO_TWI_SDA		PC4
#define GPIO_TWI_SDA_DDR	DDRC
#define GPIO_TWI_SDA_PORT	PORTC

#define GPIO_TWI_SCL		PC5
#define GPIO_TWI_SCL_DDR	DDRC
#define GPIO_TWI_SCL_PORT	PORTC

/* SPI */

#define GPIO_SPI_CLK		PB2
#define GPIO_SPI_CLK_DDR	DDRB
#define GPIO_SPI_CLK_PORT	PORTB

#define GPIO_SPI_MOSI		PB3
#define GPIO_SPI_MOSI_DDR	DDRB
#define GPIO_SPI_MOSI_PORT	PORTB

#define GPIO_SPI_MISO		PB4
#define GPIO_SPI_MISO_DDR	DDRB
#define GPIO_SPI_MISO_PORT	PORTB

#define GPIO_SPI_SS		PB5
#define GPIO_SPI_SS_DDR		DDRB
#define GPIO_SPI_SS_PORT	PORTB

#endif /* D_PINS_H */
