#ifndef D_PINS_H
#define D_PINS_H

#include <avr/io.h>

/* USART0 */

#define GPIO_USART0_TX_OFFSET	1
#define GPIO_USART0_TX_DDR	DDRD
#define GPIO_USART0_TX_PORT	PORTD

#define GPIO_USART0_RX_OFFSET	0
#define GPIO_USART0_RX_DDR	DDRD
#define GPIO_USART0_RX_PORT	PORTD

/* USART1 */

#define GPIO_USART1_TX_OFFSET	3
#define GPIO_USART1_TX_DDR	DDRD
#define GPIO_USART1_TX_PORT	PORTD

#define GPIO_USART1_RX_OFFSET	2
#define GPIO_USART1_RX_DDR	DDRD
#define GPIO_USART1_RX_PORT	PORTD

/* LCD */

#define GPIO_LCD_RS_OFFSET	4
#define GPIO_LCD_RS_DDR		DDRD
#define GPIO_LCD_RS_PORT	PORTD

#define GPIO_LCD_RW_OFFSET	5
#define GPIO_LCD_RW_DDR		DDRD
#define GPIO_LCD_RW_PORT	PORTD

#define GPIO_LCD_EN_OFFSET	6
#define GPIO_LCD_EN_DDR		DDRD
#define GPIO_LCD_EN_PORT	PORTD

#define GPIO_LCD_BL_OFFSET	7
#define GPIO_LCD_BL_DDR		DDRD
#define GPIO_LCD_BL_PORT	PORTD

/* SPI */

#define GPIO_SPI_SS_OFFSET	4
#define GPIO_SPI_SS_DDR		DDRB
#define GPIO_SPI_SS_PORT	PORTB

#define GPIO_SPI_MOSI_OFFSET	5
#define GPIO_SPI_MOSI_DDR	DDRB
#define GPIO_SPI_MOSI_PORT	PORTB

#define GPIO_SPI_MISO_OFFSET	6
#define GPIO_SPI_MISO_DDR	DDRB
#define GPIO_SPI_MISO_PORT	PORTB

#define GPIO_SPI_SCK_OFFSET	7
#define GPIO_SPI_SCK_DDR	DDRB
#define GPIO_SPI_SCK_PORT	PORTB

/* TEST SIGNAL */

#define GPIO_TESTSIG_OFFSET	3
#define GPIO_TESTSIG_DDR	DDRB
#define GPIO_TESTSIG_PORT	PORTB

/* USB */

#define GPIO_USB_DP_OFFSET	2
#define GPIO_USB_DP_DDR		DDRB
#define GPIO_USB_DP_PORT	PORTB

#define GPIO_USB_DM_OFFSET	1
#define GPIO_USB_DM_DDR		DDRB
#define GPIO_USB_DM_PORT	PORTB

/* ADC */

#define GPIO_ADC_CH0_OFFSET	0
#define GPIO_ADC_CH0_DDR	DDRA
#define GPIO_ADC_CH0_PORT	PORTA

#define GPIO_ADC_CH1_OFFSET	1
#define GPIO_ADC_CH1_DDR	DDRA
#define GPIO_ADC_CH1_PORT	PORTA

#endif /* D_PINS_H */
